repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        files: ^(magic_filter|tests)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        files: magic_filter
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        additional_dependencies: [toml]
        files: ^(magic_filter|tests)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        files: ^magic_filter
