repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        files: ^(magic_filter|tests)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        files: magic_filter
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/asottile/seed-isort-config
    rev: master
    hooks:
      - id: seed-isort-config
        additional_dependencies: [toml]
        files: ^(magic_filter|tests)

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: master # pick the isort version you'd like to use from https://github.com/pre-commit/mirrors-isort/releases
    hooks:
      - id: isort
        additional_dependencies: [toml]
        files: ^(magic_filter|tests)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.770' # pick sha/tag from https://github.com/pre-commit/mirrors-mypy
    hooks:
      - id: mypy
        files: ^magic_filter
